### ISSUE TITLE
Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by katyasichov** [chawlapalak/Url-Inspector#12]
Hey, I would like to add a feature that ignores URL patterns from the original URL list. 
If --ignore option is specified along with the file that contains URL list to ignore then the program ignores this URLs.

Please let me know if I can work on it.

**Comment by chawlapalak** [comment]
Yes, please go ahead.

**Comment by chawlapalak** [comment]
Hi Kate, 

As discussed on Slack, I checked your repo and it was working perfectly. Just one thing, kindly update the Readme file for the added feature. I will merge it then. Thanks.

**Comment by katyasichov** [comment]
Updated README with the ignore feature usage. 
Commit fc3d954213df763609a624474f5c6b67619afe0e.

**Comment by chawlapalak** [comment]
Merged. Thanks
